title: Introduction to Speech and Machine Learning
subtitle: UEF Summer School 2023
url: "https://vpspeech.github.io"
subtitle_url: "http://www.uef.fi/en/web/summerschool/machine-learning-for-speech"
baseurl: "/summerschool2023"

markdown: kramdown

google_analytics: UA-119760540-1

sass:
    style: compressed
    sass_dir: _sass
